#!/usr/bin/env bash
# Configures Nginx on a new Ubuntu machine to redirect /redirect_me to YouTube

apt-get update -y
apt-get install -y nginx

# Add the redirect in the default server block
sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
