#!/usr/bin/env bash
# Configure Nginx with a custom 404 page

# Install nginx
apt-get update -y
apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure nginx default site
cat << 'EOF' > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /custom_404.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

# Restart Nginx
service nginx restart
